# Generated by Django 6.0.5 on 2026-05-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('movie_tv', 'Movies and TV Series'), ('game', 'Games')], max_length=20)),
                ('results_ids', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('query', 'category')},
            },
        ),
    ]
