# Generated by Django 6.0.5 on 2026-05-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
