import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { GoogleOAuthProvider } from '@react-oauth/google';
import { QueryProvider } from '@/providers/queryProvider';
import AuthGate from '@/components/AuthGate';
import SideNavBar from '@/components/SideNavBar';
import Header from '@/components/Header';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <QueryProvider>
                    <GoogleOAuthProvider
                        clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}
                    >
                        <AuthGate>
                            <div className="flex h-screen w-screen overflow-hidden scrollbar-thumb-sky-900">
                                <SideNavBar />

                                <div className="flex-1 h-full overflow-y-auto relative">
                                    <Header />

                                    <main className="p-6">{children}</main>
                                </div>
                            </div>
                        </AuthGate>
                    </GoogleOAuthProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
