# Generated by Django 6.0.5 on 2026-05-29 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Series')], max_length=10)),
                ('release_year', models.CharField(blank=True, max_length=10, null=True)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('planned', 'Planned'), ('dropped', 'Dropped')], default='watching', max_length=20)),
                ('personal_rating', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_libraries', to='media.movieseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'media_item')},
            },
        ),
    ]
