# Generated by Django 6.0.5 on 2026-05-30 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieseries',
            name='last_fetched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
