# Generated by Django 6.0.5 on 2026-06-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_movieseries_last_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseries',
            name='tmdb_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
